const PRODUCTS = [
  {
    id: "cp-01",
    category: "crochet",
    title: "Cozy Blanket Crochet Pattern",
    tagline: "Step-by-step modern throw blanket for cosy evenings",
    price: 9.99,
    oldPrice: 14.99,
    rating: 4.9,
    reviews: 412,
    badge: "Bestseller",
    grad: "linear-gradient(135deg,#4B084A,#7B1D78)",
    icon: "🧶",
    description:
      "A complete, beginner-friendly PDF pattern to crochet a stunning modern throw blanket. Every row is written out with charts, stitch diagrams and video links included.",
    features: [
      "Full written pattern (PDF + mobile friendly)",
      "Stitch chart & diagram for every row",
      "Yarn & hook size recommendations",
      "Worked-in-all-sizes: baby to king",
      "Lifetime pattern updates — free",
    ],
    format: "PDF • Instant Download • 28 pages",
    imgs: [
      "https://picsum.photos/seed/df-blanket-1/800/600",
      "https://picsum.photos/seed/df-blanket-2/800/600",
      "https://picsum.photos/seed/df-blanket-3/800/600",
    ],
    video: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    links: [
      { label: "Canva template", url: "https://www.canva.com/templates/" },
      { label: "Pattern PDF file", url: "https://www.ravelry.com/patterns/library" },
    ],
  },
  {
    id: "cp-02",
    category: "crochet",
    title: "Amigurumi Bear Pattern",
    tagline: "Adorable stuffed bear — perfect gift for little ones",
    price: 6.99,
    oldPrice: null,
    rating: 4.8,
    reviews: 268,
    badge: "New",
    grad: "linear-gradient(135deg,#F6E8FF,#E3C7F0)",
    icon: "🧸",
    description:
      "Make a cute, huggable amigurumi bear with this detailed pattern. Includes photos of every step, so even first-time amigurumi makers get perfect results.",
    features: [
      "Photo tutorial for each step",
      "Tension & gauge how-to",
      "Sewing assembly guide",
      "Pattern for 12in bear",
      "Customisation ideas included",
    ],
    format: "PDF • Instant Download • 34 pages",
  },
  {
    id: "cp-03",
    category: "crochet",
    title: "Granny Square Cardigan",
    tagline: "Trendy joined granny square jacket in 3 sizes",
    price: 11.99,
    oldPrice: 15.99,
    rating: 4.7,
    reviews: 189,
    badge: null,
    grad: "linear-gradient(135deg,#5B0B52,#8B2E86)",
    icon: "🧥",
    description:
      "The viral granny square cardigan made simple. Join-as-you-go technique, written sizes for S–XXL and customisation tips for a perfect relaxed fit.",
    features: [
      "Join-as-you-go (no sewing) method",
      "Sizes S to XXL",
      "Colour placement diagrams",
      "Border & finishing instructions",
      "Stitch mystery solved with charts",
    ],
    format: "PDF • Instant Download • 42 pages",
  },
  {
    id: "cp-04",
    category: "crochet",
    title: "Mermaid Tail Blanket Pattern",
    tagline: "The ultimate snuggly mermaid tail — kids love it!",
    price: 8.99,
    oldPrice: null,
    rating: 4.8,
    reviews: 221,
    badge: null,
    grad: "linear-gradient(135deg,#3A063E,#6D1F6B)",
    icon: "🧜‍♀️",
    description:
      "A magical mermaid tail blanket with scale texture made from simple shells and chains. Works up fast in chunky yarn and fits kids to adults.",
    features: [
      "Fast with chunky yarn",
      "Toddler, child & adult sizes",
      "Scale texture technique taught",
      "Edging options (fins!)",
      "Written + diagram instructions",
    ],
    format: "PDF • Instant Download • 25 pages",
  },

  {
    id: "ai-01",
    category: "ai-prompts",
    title: "ChatGPT Mega Prompt Library",
    tagline: "500+ proven prompts for work, study & life",
    price: 14.99,
    oldPrice: 24.99,
    rating: 4.9,
    reviews: 1043,
    badge: "Bestseller",
    grad: "linear-gradient(135deg,#4B084A,#7B1D78)",
    icon: "🤖",
    description:
      "A massive, organised library of 500+ battle-tested ChatGPT prompts. Copy–paste and instantly get better outputs for marketing, coding, writing, learning and business.",
    features: [
      "500+ prompts in 12 categories",
      "Fill-in-the-blank templates",
      "Power prompts for GPT-4 & Claude",
      "Prompt engineering cheatsheet",
      "Yearly updates included free",
    ],
    format: "PDF + Notion • Instant Download",
    imgs: [
      "https://picsum.photos/seed/df-ai-1/800/600",
      "https://picsum.photos/seed/df-ai-2/800/600",
      "https://picsum.photos/seed/df-ai-3/800/600",
    ],
  },
  {
    id: "ai-02",
    category: "ai-prompts",
    title: "Midjourney Art Prompts Pack",
    tagline: "1,000 stunning image prompts for Midjourney & DALL-E",
    price: 12.99,
    oldPrice: null,
    rating: 4.8,
    reviews: 657,
    badge: "New",
    grad: "linear-gradient(135deg,#F6E8FF,#D8B4E0)",
    icon: "🎨",
    description:
      "1,000 curated art prompts across styles: cinematic, anime, 3D render, oil paint, cyberpunk and more. Includes style modifiers and aspect-ratio recipes.",
    features: [
      "1,000 prompts in 15 art styles",
      "Midjourney v6 + DALL-E 3 ready",
      "Pro style & quality modifiers",
      "Easy copy–paste Notion layout",
      "Perfect for content creators",
    ],
    format: "Notion + PDF • Instant Download",
  },
  {
    id: "ai-03",
    category: "ai-prompts",
    title: "AI Marketing Prompts",
    tagline: "Generate ads, posts & funnels in minutes",
    price: 16.99,
    oldPrice: 22.99,
    rating: 4.7,
    reviews: 534,
    badge: null,
    grad: "linear-gradient(135deg,#5B0B52,#8B2E86)",
    icon: "📣",
    description:
      "An agency-grade prompt pack for marketing teams. Create high-converting ad copy, social posts, email sequences, sales funnels and SEO content with one click.",
    features: [
      "150+ marketing frameworks",
      "Ad & funnel copy prompts",
      "Email sequence builders",
      "SEO & content calendar prompts",
      "Brand voice assistant prompts",
    ],
    format: "PDF + Sheets • Instant Download",
  },
  {
    id: "ai-04",
    category: "ai-prompts",
    title: "AI Prompts Starter Bundle",
    tagline: "The essential 100 prompts for AI beginners",
    price: 5.99,
    oldPrice: 9.99,
    rating: 4.6,
    reviews: 812,
    badge: null,
    grad: "linear-gradient(135deg,#3A063E,#6D1F6B)",
    icon: "✨",
    description:
      "Just getting started with AI? This starter bundle gives you the 100 most useful everyday prompts, neatly organised so you never stare at a blank box again.",
    features: [
      "100 essential everyday prompts",
      "Learning & study prompts",
      "Writing & brainstorming prompts",
      "Productivity & planning prompts",
      "Simple PDF layout",
    ],
    format: "PDF • Instant Download • 40 pages",
  },

  {
    id: "bt-01",
    category: "business-templates",
    title: "Pitch Deck Template",
    tagline: "Investor-ready 12-slide startup deck",
    price: 19.99,
    oldPrice: 29.99,
    rating: 4.9,
    reviews: 387,
    badge: "Bestseller",
    grad: "linear-gradient(135deg,#7B1D78,#A5559E)",
    icon: "📊",
    description:
      "A sleek, investor-tested 12-slide pitch deck in PowerPoint and Keynote. Follow the fill-in guide to raise funds with confidence — used by 2,000+ founders.",
    features: [
      "12-slide investor deck",
      "PPTX + Keynote + Canva link",
      "Fill-in-the-blank content guide",
      "Fonts, diagrams & charts included",
      "Real pitch examples",
    ],
    format: "PPTX + Keynote • Instant Download",
    imgs: [
      "https://picsum.photos/seed/df-pitch-1/800/600",
      "https://picsum.photos/seed/df-pitch-2/800/600",
      "https://picsum.photos/seed/df-pitch-3/800/600",
    ],
  },
  {
    id: "bt-02",
    category: "business-templates",
    title: "Invoice & Proposal Bundle",
    tagline: "Professional invoices & proposals for freelancers",
    price: 12.99,
    oldPrice: null,
    rating: 4.8,
    reviews: 476,
    badge: null,
    grad: "linear-gradient(135deg,#F6E8FF,#E3C7F0)",
    icon: "📄",
    description:
      "Stop losing clients to messy docs. Get editable invoices, quotes, and winning proposals in Word, Google Docs and PDF — customisable in minutes.",
    features: [
      "10 invoice templates",
      "5 proposal templates",
      "Freelance contract template",
      "Word + Google Docs + PDF",
      "Finance tracker spreadsheet",
    ],
    format: "ZIP (Docs + Sheets) • Instant Download",
  },
  {
    id: "bt-03",
    category: "business-templates",
    title: "Business Plan Template",
    tagline: "Plan your startup roadmap like the pros",
    price: 14.99,
    oldPrice: 19.99,
    rating: 4.7,
    reviews: 298,
    badge: "New",
    grad: "linear-gradient(135deg,#5B0B52,#8B2E86)",
    icon: "🗺️",
    description:
      "A complete business plan workbook with financial projections, market analysis and growth strategy. Step-by-step instructions make planning painless.",
    features: [
      "30-page guided workbook",
      "Financial forecast spreadsheets",
      "Market & competitor analysis tools",
      "SWOT & positioning frameworks",
      "Investor-ready formatting",
    ],
    format: "DOCX + XLSX • Instant Download",
  },
  {
    id: "bt-04",
    category: "business-templates",
    title: "Content Calendar System",
    tagline: "Plan 3 months of content in a weekend",
    price: 9.99,
    oldPrice: null,
    rating: 4.6,
    reviews: 189,
    badge: null,
    grad: "linear-gradient(135deg,#7B1D78,#A5559E)",
    icon: "📅",
    description:
      "The content system behind 7-figure brands. A Notion-based calendar, 100 content ideas, and a repeatable weekly workflow to stay consistent forever.",
    features: [
      "Notion content calendar",
      "100 content idea prompts",
      "Weekly planning workflow",
      "Platform-specific strategy rows",
      "Analytics review template",
    ],
    format: "Notion Template • Instant Access",
  },

  {
    id: "dr-01",
    category: "developer-resources",
    title: "React Component Library",
    tagline: "40+ production-ready UI components",
    price: 24.99,
    oldPrice: 39.99,
    rating: 4.9,
    reviews: 651,
    badge: "Bestseller",
    grad: "linear-gradient(135deg,#4B084A,#7B1D78)",
    icon: "⚛️",
    description:
      "A modern React + Tailwind component library with 40+ accessible components. Dark mode ready, fully typed, and copy–paste friendly — skip the boilerplate.",
    features: [
      "40+ copy-paste components",
      "React 18 + Tailwind CSS v3",
      "Fully typed (TS) + accessible",
      "Dark/light mode design tokens",
      "Free lifetime updates",
    ],
    format: "ZIP (Source code) • Instant Download",
  },
  {
    id: "dr-02",
    category: "developer-resources",
    title: "API Boilerplate Kit",
    tagline: "Production-ready Node.js REST API starter",
    price: 19.99,
    oldPrice: null,
    rating: 4.8,
    reviews: 409,
    badge: "New",
    grad: "linear-gradient(135deg,#F6E8FF,#D8B4E0)",
    icon: "⚙️",
    description:
      "Jump-start your backend with a secure Node.js + Express starter: auth, database, migrations, validation, logging and Docker out of the box.",
    features: [
      "Node.js + Express + Prisma",
      "JWT auth & role guards",
      "Validation & error handling",
      "Docker + CI-ready setup",
      "REST + OpenAPI docs",
    ],
    format: "ZIP (Source code) • Instant Download",
  },
  {
    id: "dr-03",
    category: "developer-resources",
    title: "CSS UI Mini-Kit",
    tagline: "Gradients, buttons, cards & effects pack",
    price: 8.99,
    oldPrice: 12.99,
    rating: 4.7,
    reviews: 523,
    badge: null,
    grad: "linear-gradient(135deg,#4B084A,#7B1D78)",
    icon: "🎨",
    description:
      "600+ curated gradients, glassmorphism cards, buttons, loaders and micro-interactions. A visual playground that makes any site look hand-crafted.",
    features: [
      "600+ modern gradients",
      "Glass & neumorphism effects",
      "80+ button styles",
      "Animated loaders & spinners",
      "Sass + vanilla CSS files",
    ],
    format: "ZIP (CSS) • Instant Download",
  },
  {
    id: "dr-04",
    category: "developer-resources",
    title: "Python Automation Scripts",
    tagline: "20 time-saving scripts for busy devs",
    price: 13.99,
    oldPrice: null,
    rating: 4.8,
    reviews: 354,
    badge: null,
    grad: "linear-gradient(135deg,#3A063E,#6D1F6B)",
    icon: "🐍",
    description:
      "Twenty practical, well-documented Python scripts that automate file organisation, web scraping, reporting, and routine dev tasks. Save hours every week.",
    features: [
      "20 commented scripts",
      "File & folder automation",
      "Web scraping helpers",
      "PDF/Excel report generators",
      "Requirements + setup guide",
    ],
    format: "ZIP (Python) • Instant Download",
  },

  {
    id: "eb-01",
    category: "ebooks",
    title: "Freelancing Mastery eBook",
    tagline: "Land high-paying clients in 90 days",
    price: 17.99,
    oldPrice: 27.99,
    rating: 4.9,
    reviews: 987,
    badge: "Bestseller",
    grad: "linear-gradient(135deg,#4B084A,#7B1D78)",
    icon: "💼",
    description:
      "A practical, no-fluff guide to building a top 1% freelance career: positioning, pricing, proposals, client psychology and scaling beyond the $10/hr trap.",
    features: [
      "90-day step-by-step plan",
      "Pricing & proposal scripts",
      "Client communication vault",
      "Personal brand framework",
      "Real case studies inside",
    ],
    format: "PDF + ePub • Instant Download • 220 pages",
  },
  {
    id: "eb-02",
    category: "ebooks",
    title: "Python for Beginners eBook",
    tagline: "From zero to your first real projects",
    price: 14.99,
    oldPrice: null,
    rating: 4.8,
    reviews: 812,
    badge: null,
    grad: "linear-gradient(135deg,#F6E8FF,#E3C7F0)",
    icon: "🐍",
    description:
      "Learn Python the fun way — short lessons, playful examples and 15 hands-on mini projects. Perfect for complete beginners who want results fast.",
    features: [
      "20 short, focused chapters",
      "15 mini projects with code",
      "Built-in quizzes & exercises",
      "Cheat-sheets at the end",
      "Companion video references",
    ],
    format: "PDF • Instant Download • 260 pages",
  },
  {
    id: "eb-03",
    category: "ebooks",
    title: "Social Media Growth eBook",
    tagline: "Grow to 100k followers organically",
    price: 15.99,
    oldPrice: 21.99,
    rating: 4.7,
    reviews: 645,
    badge: null,
    grad: "linear-gradient(135deg,#5B0B52,#8B2E86)",
    icon: "🚀",
    description:
      "The organic growth playbook used to build accounts to 100k+ on Instagram, TikTok and YouTube. Content systems, hooks and hooks that actually work.",
    features: [
      "Platform-specific playbooks",
      "Hook & viral formula bank",
      "Content pillars framework",
      "30-day content calendar",
      "Engagement growth systems",
    ],
    format: "PDF • Instant Download • 190 pages",
  },
  {
    id: "eb-04",
    category: "ebooks",
    title: "Money Mindset eBook",
    tagline: "Rewrite your money story in 30 days",
    price: 9.99,
    oldPrice: 14.99,
    rating: 4.8,
    reviews: 423,
    badge: "New",
    grad: "linear-gradient(135deg,#3A063E,#6D1F6B)",
    icon: "💰",
    description:
      "A 30-day guided journal and mindset book to heal money blocks, build healthy budgets and attract opportunities. Practical exercises included every day.",
    features: [
      "30 daily exercises",
      "Money-belief reprogramming",
      "Budget & savings templates",
      "Gratitude & abundance rituals",
      "Reflection journal pages",
    ],
    format: "PDF + Journal • Instant Download • 150 pages",
  },

  {
    id: "fa-01",
    category: "free-apps",
    title: "Invoice Maker — Free Tool",
    tagline: "Create clean invoices in under a minute",
    price: 0,
    oldPrice: null,
    rating: 4.9,
    reviews: 1240,
    badge: "FREE",
    grad: "linear-gradient(135deg,#7B1D78,#A5559E)",
    icon: "🧾",
    description:
      "A fast, free web app built in-house. Generate professional PDF invoices with your logo, taxes and currency — no sign-up, no watermark, completely free for everyone.",
    features: [
      "Free forever — no hidden charges",
      "Export professional PDF invoices",
      "Multi-currency & tax support",
      "Works on mobile & desktop",
      "Your data stays in your browser",
    ],
    format: "Free Web App • Use instantly",
  },
  {
    id: "fa-02",
    category: "free-apps",
    title: "Color Palette Studio — Free App",
    tagline: "Generate beautiful palettes in one click",
    price: 0,
    oldPrice: null,
    rating: 4.8,
    reviews: 980,
    badge: "FREE",
    grad: "linear-gradient(135deg,#F6E8FF,#D8B4E0)",
    icon: "🎨",
    description:
      "Our handmade color tool for designers and crochet makers alike. Mix, lock and copy harmonious palettes, gradients and hex codes instantly — free for life.",
    features: [
      "One-click color harmonies",
      "Copy hex / RGB / HSL codes",
      "Accessible contrast checker",
      "Export palettes as PNG / CSS",
      "Fully free, no ads",
    ],
    format: "Free Web App • Use instantly",
  },
  {
    id: "fa-03",
    category: "free-apps",
    title: "Crochet Stitch Calculator — Free",
    tagline: "Perfect gauge math, no head-scratching",
    price: 0,
    oldPrice: null,
    rating: 4.7,
    reviews: 650,
    badge: "FREE",
    grad: "linear-gradient(135deg,#4B084A,#7B1D78)",
    icon: "🧮",
    description:
      "A companion tool every crocheter needs: convert rows, stitches and hook sizes, and scale any pattern to your gauge. Developed by us, offered free to the community.",
    features: [
      "Stitch & row conversions",
      "Gauge swatch calculator",
      "Hook & yarn size guide",
      "Pattern resizing made easy",
      "100% free, no login",
    ],
    format: "Free Web App • Use instantly",
  },
  {
    id: "fa-04",
    category: "free-apps",
    title: "Password Vault — Free Security App",
    tagline: "Keep every password safe & offline",
    price: 0,
    oldPrice: null,
    rating: 4.8,
    reviews: 780,
    badge: "FREE",
    grad: "linear-gradient(135deg,#5B0B52,#8B2E86)",
    icon: "🔐",
    description:
      "A privacy-first password manager we coded from scratch. Store logins encrypted on your own device — nothing is uploaded, nothing is tracked, ever.",
    features: [
      "Encrypted local storage",
      "Strong password generator",
      "Autofill & search",
      "Works fully offline",
      "No account, no tracking",
    ],
    format: "Free Web App • Use instantly",
  },
];

const CATEGORIES = [
  { key: "crochet", name: "Crochet Patterns", icon: "🧶", color: "var(--coral)" },
  { key: "ai-prompts", name: "AI Prompts", icon: "🤖", color: "var(--violet)" },
  { key: "business-templates", name: "Business Templates", icon: "💼", color: "var(--gold)" },
  { key: "developer-resources", name: "Developer Resources", icon: "💻", color: "var(--teal)" },
  { key: "ebooks", name: "Ebooks", icon: "📚", color: "var(--blue)" },
  { key: "free-apps", name: "Free Applications", icon: "🎁", color: "var(--green)" },
];

const SITE = {
  name: "DigitalForge",
  domain: "",
  currency: "$",
  tagline: "Quality digital products, instantly delivered.",
  github: "https://github.com/suleimanaidev/digitalForgepk",
};